import type { Entity } from '@backstage/catalog-model';
import { useApiHolder } from '@backstage/core-plugin-api';
import { scmIntegrationsApiRef } from '@backstage/integration-react';
import { collectionOrigin, descriptorLocation } from './brunoEntity';

/**
 * How an operator changes a Bruno collection — which file they edit, and
 * whether Backstage can edit it for them.
 *
 * The single answer to a question the UI was previously answering in four
 * places with four slightly different wordings. Nothing about a collection is
 * editable *in* Backstage in the sense of a form that saves: the catalog is
 * derived from source control, relations are recomputed on every stitch, and no
 * catalog endpoint mutates a `spec`. What varies is only whether the change can
 * be made *from* Backstage — by opening a pull request against the file that
 * does own it — or has to be made by hand somewhere Backstage cannot reach.
 *
 *  - `pull-request` — a descriptor in an SCM the plugin can write to. Backstage
 *    opens the pull request; the change lands when it is merged.
 *  - `descriptor` — a descriptor in an SCM the plugin cannot write to. The
 *    operator edits the file; we name it and say exactly what to change.
 *  - `app-config` — a `bruno.collections[]` entry. No descriptor exists; the
 *    operator edits `app-config.yaml` and restarts Backstage.
 *  - `local-file` — a descriptor on the Backstage host's disk. Same as above,
 *    minus the restart.
 *  - `unknown` — the entity names no location we can resolve.
 */
export type ChangeRoute
  = | {
    via: 'pull-request' | 'descriptor';
    descriptorUrl: string;
    /** The descriptor was generated by this plugin rather than hand-written. */
    createdInBackstage: boolean;
  }
  | { via: 'app-config' }
  | { via: 'local-file' }
  | { via: 'unknown' };

/**
 * The route for one collection.
 *
 * `canOpenPullRequest` is injected rather than looked up so this stays pure and
 * testable; {@link useChangeRoute} supplies the real one. It defaults to `false`
 * — a caller that has no SCM context gets told to edit the file by hand, which
 * is always true advice, rather than being promised a button that is not there.
 */
export function changeRoute(
  entity: Entity,
  canOpenPullRequest: (descriptorUrl: string) => boolean = () => false
): ChangeRoute {
  const origin = collectionOrigin(entity);
  if (origin === 'config') {
    return { via: 'app-config' };
  }
  if (origin === 'file') {
    return { via: 'local-file' };
  }

  const location = descriptorLocation(entity);
  if (location.kind !== 'url') {
    return { via: 'unknown' };
  }
  return {
    via: canOpenPullRequest(location.target) ? 'pull-request' : 'descriptor',
    descriptorUrl: location.target,
    createdInBackstage: origin === 'ui'
  };
}

/**
 * {@link changeRoute} with the real pull-request capability filled in.
 *
 * Pull requests are opened against GitHub only — `lib/unlinkPr.ts` speaks the
 * GitHub contents/pulls API and nothing else — and the host app's configured
 * integrations decide which URLs are GitHub, including self-hosted ones. Hence
 * `scmIntegrationsApiRef` rather than this plugin's own `scmProviderFromUrl`,
 * which guesses from the hostname and is only meant for validating pasted
 * input.
 *
 * `useApiHolder`, not `useApi`: a host app is not obliged to register the SCM
 * integrations API, and `useApi` throws at RENDER time for a missing one, which
 * would take down every card that wants to explain itself.
 */
export function useChangeRoute(entity: Entity): ChangeRoute {
  const scmIntegrations = useApiHolder().get(scmIntegrationsApiRef);
  return changeRoute(
    entity,
    (url) => scmIntegrations?.byUrl(url)?.type === 'github'
  );
}

/** A short "Managed by" value for the entity header. */
export function changeRouteLabel(route: ChangeRoute): string {
  switch (route.via) {
    case 'app-config':
      return 'app-config.yaml';
    case 'local-file':
      return 'catalog-info.yaml (on disk)';
    case 'unknown':
      return 'Unknown';
    default:
      return route.createdInBackstage
        ? 'catalog-info.yaml (added in Backstage)'
        : 'catalog-info.yaml';
  }
}
